# Generated by Django 5.1.15 on 2026-02-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subjects',
            field=models.TextField(blank=True, help_text='Comma separated', verbose_name='विषय'),
        ),
    ]
